# Solution to Project Euler problem 2
# https://github.com/bekowashere/project-euler-solutions

"""
Problem:
Each new term in the Fibonacci is sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms
"""


def compute():
    answer = 0
    first = 1
    second = 2
    while first <= 4000000:
        if first % 2 == 0:
            answer += first
        first, second = second, first + second
    return str(answer)


print(compute())
